FROM nginx:alpine

# Copy custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy static files
COPY frontend_build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
